<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2011-09-01 11:20

$extensionPath = \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('gridelements');
return array(
	'tx_gridelements_cmoptions'							=> $extensionPath . 'lib/class.tx_gridelements_cmoptions.php',
	'tx_gridelements_itemsprocfunc_abstract'			=> $extensionPath . 'lib/itemsprocfuncs/class.tx_gridelements_itemsprocfunc_abstract.php',
	'tx_gridelements_itemsprocfunc_colposlist'			=> $extensionPath . 'lib/itemsprocfuncs/class.tx_gridelements_itemsprocfunc_colposlist.php',
	'tx_gridelements_itemsprocfunc_ctypelist'			=> $extensionPath . 'lib/itemsprocfuncs/class.tx_gridelements_itemsprocfunc_ctypelist.php',
	'tx_gridelements_drawitemhook'						=> $extensionPath . 'lib/class.tx_gridelements_drawitemhook.php',
	'tx_gridelements_layoutsetup'						=> $extensionPath . 'lib/class.tx_gridelements_layoutsetup.php',
	'tx_gridelements_tceformshook'						=> $extensionPath . 'lib/class.tx_gridelements_tceformshook.php',
	'tx_gridelements_tcemainhook'						=> $extensionPath . 'lib/class.tx_gridelements_tcemainhook.php',
	'tx_gridelements_tcemain_abstract'					=> $extensionPath . 'lib/tcemain/class.tx_gridelements_tcemain_abstract.php',
	'tx_gridelements_tcemain_preprocessfieldarray'		=> $extensionPath . 'lib/tcemain/class.tx_gridelements_tcemain_preProcessFieldArray.php',
	'tx_gridelements_tcemain_processcmdmap'				=> $extensionPath . 'lib/tcemain/class.tx_gridelements_tcemain_processCmdmap.php',
	'tx_gridelements_tcemain_moverecord'				=> $extensionPath . 'lib/tcemain/class.tx_gridelements_tcemain_moveRecord.php',
	'tx_gridelements_tt_content'						=> $extensionPath . 'lib/class.tx_gridelements_tt_content.php',
	'tx_gridelements_wizarditemshook'					=> $extensionPath . 'lib/class.tx_gridelements_wizarditemshook.php',
	'tx_gridelements_helper'							=> $extensionPath . 'lib/class.tx_gridelements_helper.php',
	'tx_gridelements_view'								=> $extensionPath . 'view/class.tx_gridelements_view.php',
	'wrapperfort3libbefunc'								=> $extensionPath . 'lib/wrapperForT3libBeFunc.php',

	// hooks
	'tx_gridelements_pagerendererhook'					=> $extensionPath . 'hooks/class.tx_gridelements_pagerendererhook.php',
	'tx_gridelements_db_listhook'						=> $extensionPath . 'hooks/class.tx_gridelements_db_listhook.php',
	'tx_gridelements_db_list_extrahook'					=> $extensionPath . 'hooks/class.tx_gridelements_db_list_extrahook.php',

);
