<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2013-04-21 18:09

$extensionPath = t3lib_extMgm::extPath('gridelements');
$extensionClassesPath = $extensionPath . 'Classes/';
return array(
	'tx_gridelements_cmoptions' => $extensionPath . 'lib/class.tx_gridelements_cmoptions.php',
	'tx_gridelements_tt_content' => $extensionPath . 'lib/class.tx_gridelements_tt_content.php',
);
?>